Repository TicketWar/backend, pull requests merged in 2024-04, with the labels that each got.

#3 chore: application.properties를 yaml 방식으로 수정
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/yaml/application-local.yml
  src/main/resources/yaml/log.yml
Labels: CHORE

#12 [Remerge] Customer Service 레이어 구현
  src/main/java/com/ticketwar/ticketwar/common/entity/trackable/CreatedAndUpdatedTimeTrackable.java
  src/main/java/com/ticketwar/ticketwar/common/entity/trackable/CreatedTimeTrackable.java
  src/main/java/com/ticketwar/ticketwar/common/entity/trackable/UpdatedTimeTrackable.java
  src/main/java/com/ticketwar/ticketwar/common/interfaces/EntityConvertable.java
  src/main/java/com/ticketwar/ticketwar/configure/DatabaseInitializer.java
  src/main/java/com/ticketwar/ticketwar/customer/controller/CustomerController.java
  src/main/java/com/ticketwar/ticketwar/customer/dto/CustomerDto.java
  src/main/java/com/ticketwar/ticketwar/customer/dto/CustomerReqDto.java
  src/main/java/com/ticketwar/ticketwar/customer/dto/CustomerResDto.java
  src/main/java/com/ticketwar/ticketwar/customer/entity/Customer.java
  src/main/java/com/ticketwar/ticketwar/customer/repository/CustomerRepository.java
  src/main/java/com/ticketwar/ticketwar/customer/service/CustomerQueryService.java
  src/main/java/com/ticketwar/ticketwar/customer/service/CustomerService.java
  src/main/java/com/ticketwar/ticketwar/customer/utils/CustomerMapper.java
  src/main/java/com/ticketwar/ticketwar/order/entity/Order.java
  src/main/java/com/ticketwar/ticketwar/order/repository/OrderRepository.java
  src/main/java/com/ticketwar/ticketwar/performance/entity/Performance.java
  src/main/java/com/ticketwar/ticketwar/performance/repository/PerformanceRepository.java
  src/main/java/com/ticketwar/ticketwar/performance/service/PerformanceService.java
  src/main/java/com/ticketwar/ticketwar/seat/entity/Seat.java
  src/main/java/com/ticketwar/ticketwar/seat/repository/SeatRepository.java
  src/main/java/com/ticketwar/ticketwar/ticket/entity/Ticket.java
  src/main/java/com/ticketwar/ticketwar/ticket/repository/TicketRepository.java
  src/main/java/com/ticketwar/ticketwar/ticket/service/TicketService.java
  src/main/resources/application.yml
  src/main/resources/yaml/local.yml
  src/main/resources/yaml/prod.yml
  src/test/java/com/ticketwar/ticketwar/customer/repository/CustomerRepositoryTest.java
  src/test/java/com/ticketwar/ticketwar/customer/service/CustomerQueryServiceTest.java
  src/test/java/com/ticketwar/ticketwar/customer/service/CustomerServiceTest.java
Labels: FEAT, FIX

#19 [fix] Order, Ticket, Customer 엔티티 변경사항 반영 / Controller "...s" 복수형으로 변경 #18
  src/main/java/com/ticketwar/ticketwar/configure/DatabaseInitializer.java
  src/main/java/com/ticketwar/ticketwar/customer/entity/Customer.java
  src/main/java/com/ticketwar/ticketwar/customer/service/CustomerQueryService.java
  src/main/java/com/ticketwar/ticketwar/customer/service/CustomerService.java
  src/main/java/com/ticketwar/ticketwar/customer/utils/CustomerMapper.java
  src/main/java/com/ticketwar/ticketwar/order/entity/Order.java
  src/main/java/com/ticketwar/ticketwar/performance/entity/Performance.java
  src/main/java/com/ticketwar/ticketwar/seat/entity/Seat.java
  src/main/java/com/ticketwar/ticketwar/ticket/entity/Ticket.java
  src/main/java/com/ticketwar/ticketwar/user/controller/UserController.java
  src/main/java/com/ticketwar/ticketwar/user/dto/UserReqDto.java
  src/main/java/com/ticketwar/ticketwar/user/dto/UserResDto.java
  src/main/java/com/ticketwar/ticketwar/user/entity/User.java
  src/main/java/com/ticketwar/ticketwar/user/repository/UserRepository.java
  src/main/java/com/ticketwar/ticketwar/user/service/UserQueryService.java
  src/main/java/com/ticketwar/ticketwar/user/service/UserService.java
  src/main/java/com/ticketwar/ticketwar/user/utils/UserMapper.java
  src/test/java/com/ticketwar/ticketwar/customer/repository/CustomerRepositoryTest.java
  src/test/java/com/ticketwar/ticketwar/customer/service/CustomerServiceTest.java
  src/test/java/com/ticketwar/ticketwar/user/repository/UserRepositoryTest.java
  src/test/java/com/ticketwar/ticketwar/user/service/UserQueryServiceTest.java
  src/test/java/com/ticketwar/ticketwar/user/service/UserServiceTest.java
Labels: FIX

#13 Feat: CustomException 구현 #11
  src/main/java/com/ticketwar/ticketwar/exception/CustomException.java
  src/main/java/com/ticketwar/ticketwar/exception/ExceptionStatus.java
  src/main/java/com/ticketwar/ticketwar/exception/GlobalExceptionHandler.java
Labels: FEAT

#22 FEAT: CustomException 도입 #20 #13
  src/main/java/com/ticketwar/ticketwar/exception/ExceptionStatus.java
  src/main/java/com/ticketwar/ticketwar/user/service/UserService.java
  src/test/java/com/ticketwar/ticketwar/user/service/UserServiceTest.java
Labels: FEAT
